### ISSUE TITLE
Removal of ip/nets from group fails

### ISSUE THREAD

**Issue by zoil66** [mighq/puppet-ipset#11]
Sync script should work using the swap flag. For me it is failing to add or remove consistently in memory.  The file gets changes and the refresh is triggered but the set does not alter.  Possibly the set file is not writing to disk fast enough for the bash script to pick up.

**Comment by mighq** [comment]
I just noticed it too, thanks. It was a sync script bug introduced when I added "-v" option (in v0.3.2). See 350aa6c6307f1ad745534aa53f8bc0bd6bdd71d7. Fixed in v0.4.1.
I apologize for troubles caused.
