### ISSUE TITLE
still tries to reload ipset if not all optional parameters are given in puppet

### ISSUE THREAD

**Issue by jovandeginste** [mighq/puppet-ipset#5]
If I don't specify hashsize or maxelem, the diff between the hdr and the ipset is not correct:

```
< create icts_servers_ipv6 hash:net family inet6 hashsize 1024 maxelem 65536
> create icts_servers_ipv6 hash:net family inet6
```

If I specify hashsize and maxelem, this is no longer an issue.

Is this easily fixed?

The real problem is that it tries to destroy the ipset to refresh, which can not be done since it is used (in this case by iptables). It should actually create a second ipset, populate it, and then swap it with the old one (and then destroy the old one) - this only works if the hdr's are equal...

```
swap FROM-SETNAME TO-SETNAME
        Swap the contect of two existing sets
```

**Comment by mighq** [comment]
fixed in commit 185cd7e2a9e03c16d8dc66c9759e707609311878
