### ISSUE TITLE
Set config_path default to /etc/ipset.d

### ISSUE THREAD

**Issue by bahner** [mighq/puppet-ipset#8]
Hepp!

I am using the module with debian and it works OK. BUT I need to change ipset::params::config_path so that default is "/etc/ipset.d/".

It would be nice if you would do the same or add an osfamily = Debian case.

Kind regards,
bahner

**Comment by mighq** [comment]
patched in commit 13f95d84bc3c3387f4dd6d1da970652e9a55e498
